/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.vista;

import hotel.Conexion;
import hotel.modelo.HabitacionData;
import hotel.modelo.Reserva;
import hotel.modelo.ReservaData;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fati
 */
public class BuscarReservaPanel extends javax.swing.JPanel {
    private Reserva reserva;
    private ArrayList<Reserva> lReservas;
    private Conexion conexion;
    private DefaultTableModel dataModel;

    /**
     * Creates new form BuscarReserva
     */
    public BuscarReservaPanel() {
        conexion = new Conexion("jdbc:mysql://localhost/hotel", "root", "");
        initComponents();
        setTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoBusqueda = new javax.swing.JTextField();
        botonBusqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        botonTerminarReserva = new javax.swing.JButton();

        botonBusqueda.setText("Buscar");
        botonBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusquedaActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        botonTerminarReserva.setText("TERMINAR RESERVA");
        botonTerminarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBusqueda))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(botonTerminarReserva)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBusqueda))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonTerminarReserva)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusquedaActionPerformed
        buscarReservas();
        setTableContent();
    }//GEN-LAST:event_botonBusquedaActionPerformed

    private void buscarReservas() {
        String huesped;
        ReservaData rd = new ReservaData(conexion);
        huesped = campoBusqueda.getText();
        
        try {
            int dni = Integer.parseInt(huesped);
            lReservas = rd.buscarReservasPorHuesped(dni);
        } catch(NumberFormatException e) {
            lReservas = rd.buscarReservasPorHuesped(huesped);
        }
        
    }
    
    private void botonTerminarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarReservaActionPerformed
        ReservaData rd = new ReservaData(conexion);
        HabitacionData hd = new HabitacionData(conexion);
        int columns = table.getColumnCount();
        int row = table.getSelectedRow();
        String columnName;
        
        int nHab = -1;
        
        for(int i = 0; i < columns; i++) {
            columnName = table.getColumnName(i);
            
            if(columnName.equals("N°")) {
                nHab = (int) table.getValueAt(row, i);
            }      
        }
        
        if(nHab != -1) {
            rd.finalizarReserva(nHab);
            hd.setEstadoHabitacion(nHab, false);
        }
        
        buscarReservas();
        setTableContent();
    }//GEN-LAST:event_botonTerminarReservaActionPerformed
            
    private void setTableModel() {
        String col[] = {
            "N°", 
            "Habitacion", 
            "DNI", 
            "Huesped", 
            "Fecha Entrada", 
            "Fecha Salida", 
            "Cantidad De Personas", 
            "Importe",
            "Estado"
        };
        
        dataModel = new DefaultTableModel(col, 0);
        
        table.setModel(dataModel);
        table.setDragEnabled(false);
    }
    
    private void setTableContent() {
        for(int i = dataModel.getRowCount(); i > 0; i--) {
            dataModel.removeRow(i - 1);
        }
        
        for(Reserva r : lReservas) {
            Object row[] = {
                r.getNroReserva(), 
                r.getHabitacion().getNHabitacion(), 
                r.getHuesped().getDni(),
                r.getHuesped().getNombre(),
                r.getFechaEntrada().toString(),
                r.getFechaSalida().toString(),
                r.getCantidadDePersonas(),
                r.getImporteTotal(),
                r.getEstado() ? "activa" : "inactiva"
            };
            
            dataModel.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBusqueda;
    private javax.swing.JButton botonTerminarReserva;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
