/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.vista;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import AppPackage.AnimationClass;
import hotel.Conexion;
import hotel.modelo.Habitacion;
import hotel.modelo.HabitacionData;
import hotel.modelo.TipoHabitacion;
import hotel.modelo.TipoHabitacionData;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class Habitacion_vista extends javax.swing.JFrame {
private Conexion conexion;
 private TipoHabitacionData tipohabitaciondata;
 private HabitacionData habitaciondata;
 private DefaultTableModel modelo;
      
 
    public Habitacion_vista() {
        
        initComponents();
        
        //esta sentencia lo que hace es que al largar la vista se centra en la pantalla.
        this.setLocationRelativeTo(null);
        
        try {
            //se crea una conexion del tipo Conexion donde se especifica la base donde se va a conectar.
            conexion = new Conexion("jdbc:mysql://localhost/hotel", "root", "");
            //se crea un objeto de tipohabitacion data y se manda como parametro la conexion previamente creada.
            tipohabitaciondata = new TipoHabitacionData(conexion);
            //se crea un objeto de habitaciondata y tambien se manda como parametro la conexion previamente creada
            habitaciondata=new HabitacionData(conexion); 
            //se crea un objeto del tipo defaulttablemodel esto nos permitira modelar la tabla cuando se inicie la vista.
            modelo=new DefaultTableModel();
            //este nos permite cargar los tipo de habitacion en el combox cuando se inicie la vista
            tipohabitaciondata.cargarComboxConTipoHabitacion(jComboBoxTipoHabitacion);
            //este metodo nos arma la cabecera con los nombres de la columna
            armaCabeceraTabla();
            
        } catch (Exception e) {
            
           JOptionPane.showMessageDialog(null,"se produjo un error al conectar con la base de datos: " + e);
        }
        
        
       
       
    }
       public void armaCabeceraTabla(){
           
            //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("Numero de Habitacion");
        columnas.add("Piso");
        columnas.add("Estado");
        columnas.add("Tipo de Habitacion");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
       jTableHabitaciones.setModel(modelo);
       }
       
       public void borraFilasTabla(){
           
           int a =modelo.getRowCount()-1;
           
            System.out.println("Tabla "+a);
            
            for(int i=a;i>=0;i--){
                modelo.removeRow(i );
                System.out.println("Tabla "+i);
            }
           
       }
       
       
       
    
    
  
  
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOcupadoDesocupado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelOpciones = new javax.swing.JLabel();
        jLabelMinimizar = new javax.swing.JLabel();
        jLabelCancelar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTipoHabitacion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHabitaciones = new javax.swing.JTable();
        jLabelMenu = new javax.swing.JLabel();
        jLabelHuesped = new javax.swing.JLabel();
        jLabelReserva = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonDesocupado = new javax.swing.JRadioButton();
        jRadioButtonOcupado = new javax.swing.JRadioButton();
        jTextFieldPiso = new javax.swing.JTextField();
        jTextFieldNumeroHabitacion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelAgregarHabitacion = new javax.swing.JLabel();
        jLabelMostrarHabitaciones = new javax.swing.JLabel();
        jTextFieldcantidadHabitacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelBorrarHabitacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N
        jLabelOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOpcionesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelOpcionesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelOpcionesMouseReleased(evt);
            }
        });
        jPanel1.add(jLabelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 30));

        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimize_1.png"))); // NOI18N
        jLabelMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 30, 30));

        jLabelCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jLabelCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCancelarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCancelarMouseReleased(evt);
            }
        });
        jPanel1.add(jLabelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("HABITACIONES");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo De Habitacion");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jComboBoxTipoHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxTipoHabitacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jComboBoxTipoHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar..." }));
        jPanel2.add(jComboBoxTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 140, 30));

        jTableHabitaciones.setBackground(new java.awt.Color(255, 255, 255));
        jTableHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableHabitaciones.setEnabled(false);
        jTableHabitaciones.setGridColor(new java.awt.Color(102, 204, 255));
        jScrollPane1.setViewportView(jTableHabitaciones);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 700, 170));

        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_ventana.png"))); // NOI18N
        jLabelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseReleased(evt);
            }
        });
        jPanel2.add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 40, 30));

        jLabelHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guest_ventana.png"))); // NOI18N
        jLabelHuesped.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHuesped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHuespedMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelHuespedMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelHuespedMouseReleased(evt);
            }
        });
        jPanel2.add(jLabelHuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 50, 30, 40));

        jLabelReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/online-booking_ventana.png"))); // NOI18N
        jLabelReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReservaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelReservaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelReservaMouseReleased(evt);
            }
        });
        jPanel2.add(jLabelReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 100, 40, 40));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Numero de Habitacion");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Piso");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jRadioButtonDesocupado.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupOcupadoDesocupado.add(jRadioButtonDesocupado);
        jRadioButtonDesocupado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jRadioButtonDesocupado.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonDesocupado.setText("Desocupado");
        jRadioButtonDesocupado.setBorder(null);
        jRadioButtonDesocupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDesocupadoActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonDesocupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jRadioButtonOcupado.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupOcupadoDesocupado.add(jRadioButtonOcupado);
        jRadioButtonOcupado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jRadioButtonOcupado.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonOcupado.setText("Ocupado");
        jRadioButtonOcupado.setBorder(null);
        jRadioButtonOcupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOcupadoActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonOcupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 90, -1));

        jTextFieldPiso.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPiso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextFieldPiso.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPiso.setBorder(null);
        jPanel2.add(jTextFieldPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 40, -1));

        jTextFieldNumeroHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNumeroHabitacion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextFieldNumeroHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNumeroHabitacion.setBorder(null);
        jPanel2.add(jTextFieldNumeroHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 50, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(102, 204, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 40, 10));

        jSeparator2.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator2.setForeground(new java.awt.Color(102, 204, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 50, 10));

        jLabelAgregarHabitacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelAgregarHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAgregarHabitacion.setText("Agregar Habitacion");
        jLabelAgregarHabitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAgregarHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgregarHabitacionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelAgregarHabitacionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelAgregarHabitacionMouseReleased(evt);
            }
        });
        jPanel2.add(jLabelAgregarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jLabelMostrarHabitaciones.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMostrarHabitaciones.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMostrarHabitaciones.setText("Mostrar Habitaciones");
        jLabelMostrarHabitaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMostrarHabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMostrarHabitacionesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMostrarHabitacionesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMostrarHabitacionesMouseReleased(evt);
            }
        });
        jPanel2.add(jLabelMostrarHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 150, -1));

        jTextFieldcantidadHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldcantidadHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldcantidadHabitacion.setBorder(null);
        jPanel2.add(jTextFieldcantidadHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 30, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cantidad de Habitacion:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator3.setForeground(new java.awt.Color(102, 204, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 30, 10));

        jLabelBorrarHabitacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelBorrarHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBorrarHabitacion.setText("Borrar Habitacion");
        jLabelBorrarHabitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBorrarHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBorrarHabitacionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBorrarHabitacionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelBorrarHabitacionMouseReleased(evt);
            }
        });
        jPanel2.add(jLabelBorrarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelOpcionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpcionesMousePressed
        jLabelOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_in.png")));
    }//GEN-LAST:event_jLabelOpcionesMousePressed

    private void jLabelOpcionesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpcionesMouseReleased
        jLabelOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png")));
    }//GEN-LAST:event_jLabelOpcionesMouseReleased
//BOTON OPCIONES.
    private void jLabelOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpcionesMouseClicked
          
        AnimationClass menu =new AnimationClass();
       menu.jLabelXRight(-40, 10, 10, 5, jLabelMenu);
       
       
       //mueve el icono menu a la izquierda
       AnimationClass menuu =new AnimationClass();
       menuu.jLabelXLeft(10, -40, 10, 5, jLabelMenu);
        
        //mueve el icono reserva a la izquieda
        AnimationClass reserva = new AnimationClass();
       reserva.jLabelXRight(-40, 10, 10, 5, jLabelReserva);
       
       //mueve el icono reserva a la derecha 
       AnimationClass reservaa = new AnimationClass();
       reservaa.jLabelXLeft(10, -40,10,5, jLabelReserva);
       
       //mueve el icono huesped a la derecha
       AnimationClass huesped =new AnimationClass();
       menu.jLabelXRight(-40, 10, 10, 5, jLabelHuesped);
       
       //mueve el icono huesped a la izquierda
       AnimationClass huespedd =new AnimationClass();
       menuu.jLabelXLeft(10, -40, 10, 5, jLabelHuesped);
             
    }//GEN-LAST:event_jLabelOpcionesMouseClicked

    private void jLabelMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMousePressed
        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_ventana_in.png")));
    }//GEN-LAST:event_jLabelMenuMousePressed

    private void jLabelMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseReleased
        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_ventana.png")));
    }//GEN-LAST:event_jLabelMenuMouseReleased

    private void jLabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseClicked
       Menu menu =new Menu();
       menu.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabelMenuMouseClicked

    private void jLabelHuespedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHuespedMousePressed
         jLabelHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guest_in_ventana.png")));
    }//GEN-LAST:event_jLabelHuespedMousePressed

    private void jLabelHuespedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHuespedMouseReleased
       jLabelHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guest_ventana.png")));
    }//GEN-LAST:event_jLabelHuespedMouseReleased

    private void jLabelHuespedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHuespedMouseClicked
        Huesped_vista huesped =new Huesped_vista();
       huesped.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabelHuespedMouseClicked

    private void jLabelReservaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservaMousePressed
     jLabelReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/online-booking_ventana_in.png")));
    }//GEN-LAST:event_jLabelReservaMousePressed

    private void jLabelReservaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservaMouseReleased
        jLabelReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/online-booking_ventana.png")));
    }//GEN-LAST:event_jLabelReservaMouseReleased

    private void jLabelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseClicked
         this.setState(Habitacion_vista.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizarMouseClicked

    private void jLabelCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarMousePressed
        jLabelCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel_in.png")));
    }//GEN-LAST:event_jLabelCancelarMousePressed

    private void jLabelCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarMouseReleased
       jLabelCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png")));
    }//GEN-LAST:event_jLabelCancelarMouseReleased

    private void jLabelCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarMouseClicked
      
        //creo un objeto Icon y le asigno la imagen del icono 
       Icon icono = new ImageIcon(getClass().getResource("/imagenes/logo_ventana.png"));
        
        int dialogoboton = JOptionPane.YES_NO_OPTION;
       int resultado = JOptionPane.showConfirmDialog(null, "Desea salir? ", "Salir",dialogoboton,JOptionPane.QUESTION_MESSAGE,icono);
       //utilizo el if para hacer una comparacion si el usuario da en si sale de la ventana y si le da no sigue trabajando 
       if (resultado==0){
           
          System.exit(0);
       }       

    }//GEN-LAST:event_jLabelCancelarMouseClicked

    private void jLabelReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservaMouseClicked
     
     //se crea un objeto de tio reserva vista para que luego al hacerle clik al boton cambia de pestaña   
     Reserva_vista reserva=new Reserva_vista();
     //hace visible la pestaña reserva vista
     reserva.setVisible(true);
     //cierra la ventana anterior
     dispose();
     
    }//GEN-LAST:event_jLabelReservaMouseClicked

    private void jRadioButtonOcupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOcupadoActionPerformed
       
    }//GEN-LAST:event_jRadioButtonOcupadoActionPerformed

    private void jLabelAgregarHabitacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarHabitacionMousePressed
        jLabelAgregarHabitacion.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelAgregarHabitacionMousePressed

    private void jLabelAgregarHabitacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarHabitacionMouseReleased
         jLabelAgregarHabitacion.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelAgregarHabitacionMouseReleased

    private void jRadioButtonDesocupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDesocupadoActionPerformed
      
          
    
    }//GEN-LAST:event_jRadioButtonDesocupadoActionPerformed
   //BOTON AGREGAR HABITACION
    private void jLabelAgregarHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarHabitacionMouseClicked
        try {
            
            
       //creamos una variable de tipo int que recibe el numero de la habitacion que se escribe en el texfiel de la interfaz, como al ser de tipo String lo que capta el texfiel se transforma con la sentencia parceint a un numero.     
        int nro_habitacion=Integer.parseInt(jTextFieldNumeroHabitacion.getText());
       // lo mismo que el numero de habitacion nada mas que en este caso se guarda el numero del piso
        int piso=Integer.parseInt(jTextFieldNumeroHabitacion.getText());
      // se crea un objeto del tipo tipohabitacion que recibe como parametro el id que es captado del combox.
        TipoHabitacion th=new TipoHabitacion((int) jComboBoxTipoHabitacion.getSelectedIndex());
      // se crea una variable de tipo boolean y se le asigna false ya que al agregar una habitacion por defecto su estado es false 
        boolean estado=false;
      
       // luego de crear todas las variables se crea un objeto de tipo habitacion y se manda los parametro para construirlo.
       Habitacion habitacion=new Habitacion(nro_habitacion,piso,estado,th);
        //luego de haber creado el objeto habitacion, utilizando habitaciondata creado previamente al principio del programa se llama el procedimiento guardarhabitacion que toma como parametro una habitacion ya previamente creada.   
        habitaciondata.guardarHabitacion(habitacion);
        
            
 JOptionPane.showMessageDialog(null,"Habitacion ingresada con exito");
            
            
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(null,"Erro al guardar Habitacion: "+ e);
            
            
        }
       
        
    }//GEN-LAST:event_jLabelAgregarHabitacionMouseClicked
     //AL PRESIONAR EL BOTON MOSTRAR REALIZA LA SIGUIENTE ACCION
    private void jLabelMostrarHabitacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMostrarHabitacionesMousePressed
         jLabelMostrarHabitaciones.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelMostrarHabitacionesMousePressed
    //AL SOLTAR EL BOTON MOSTRAR REALIZA LA SIGUIENTE ACCION
    private void jLabelMostrarHabitacionesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMostrarHabitacionesMouseReleased
       jLabelMostrarHabitaciones.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelMostrarHabitacionesMouseReleased
    // BOTON MOSTRAR HABITACION.
    private void jLabelMostrarHabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMostrarHabitacionesMouseClicked
        //este metodo hace que cada vez que aprietes el boton borre las filas que se encuentran en la tabla 
        borraFilasTabla();
        
       //obtenemos el indice del elemento que tenemos cargado en el combox.
        int idtipo = jComboBoxTipoHabitacion.getSelectedIndex();
    //abrimos una condicion en donde vemos si el radiobuttondesocupado esta seleccionado entonces hacemos la siguientes setencias.
        if(jRadioButtonDesocupado.isSelected()){
            
          //creamos una lista que va a recibir  los tipos de habitaciones que van a estar desocupadas ya que se le manda un true y el indice que capturamos del combox que sera el id del tipo de habitacion  
         ArrayList <Habitacion> listaHabitacion=habitaciondata.obtenerHabitacionPorTipo(false,idtipo);
        
         //Llenar filas
        for(Habitacion m: listaHabitacion){
        
            //Comparo por los id o sobreescribo el método equals 
            if(m.getTipoHabitacion().getId()==idtipo){
            //lleno las filas con los elementos obtenidos de la base de datos.
            modelo.addRow(new Object[]{m.getNHabitacion(),m.getPiso(),m.getEstado()?"Ocupada":"libre",m.getTipoHabitacion().getCategoria()});
            }
          
          
        }
        
        //este metodo recibe como parametro el estado de la habitacion ,id_tipo_habitacion(idtipo)y el texfiel donde se visualiza el numero de habitaciones de ese tipo. 
         habitaciondata.cuentaHabitacion(true,idtipo, jTextFieldcantidadHabitacion);
          
      
    
    //abrimos otro if  en donde vemos si el radiobuttonocupado esta seleccionado entonces hacemos la siguientes setencias.
        }else if (jRadioButtonOcupado.isSelected()){
            
            //creamos una lista que va a recibir  los tipos de habitaciones que van a estar ocupados ya que se le manda un false y el indice que capturamos del combox que sera el id del tipo de habitacion
             ArrayList <Habitacion> listaHabitacion=habitaciondata.obtenerHabitacionPorTipo(true,idtipo);
        
         //Llenar filas
        for(Habitacion m: listaHabitacion){
        
            //Comparo por los id o sobreescribo el método equals 
            if(m.getTipoHabitacion().getId()==idtipo){
            //lleno las filas con los elementos obtenidos de la base de datos.
            modelo.addRow(new Object[]{m.getNHabitacion(),m.getPiso(),m.getEstado()?"Ocupada":"libre",m.getTipoHabitacion().getCategoria()});
            }
          
         
        }
         //este metodo recibe como parametro el estado de la habitacion ,id_tipo_habitacion(idtipo)y el texfiel donde se visualiza el numero de habitaciones de ese tipo
         habitaciondata.cuentaHabitacion(false,idtipo, jTextFieldcantidadHabitacion);
          //si  no esta seleccionado ninguno lo que hace esta sentencia es mostrar ocupados y desocupados juntos.
        }else{
            
           ArrayList <Habitacion> listaHabitacion=habitaciondata.obtenerHabitacionPorTipo(idtipo);
           
            //Llenar filas
        for(Habitacion m: listaHabitacion){
        
            //Comparo por los id o sobreescribo el método equals 
            if(m.getTipoHabitacion().getId()==idtipo){
            
            modelo.addRow(new Object[]{m.getNHabitacion(),m.getPiso(),m.getEstado(),m.getTipoHabitacion().getCategoria()});
            }
          
          
        }
        
        
         habitaciondata.CuentaHabitacionsinestado(idtipo, jTextFieldcantidadHabitacion);
          
            
           
        }
      
     
    }//GEN-LAST:event_jLabelMostrarHabitacionesMouseClicked
      //AL PRESIONAR EL BOTON BORRAR REALIZA LA SIGUIENTE ACCION
    private void jLabelBorrarHabitacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBorrarHabitacionMousePressed
      
        //pintamos la letra de  gris al hacer clik 
        jLabelBorrarHabitacion.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelBorrarHabitacionMousePressed
    //AL SOLTAR BOTON BORRAR REALIZA LA SIGUIENTE ACCION
    private void jLabelBorrarHabitacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBorrarHabitacionMouseReleased
       //pintamos la letra de color negro al soltar el clik
        jLabelBorrarHabitacion.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelBorrarHabitacionMouseReleased
   //BOTON BORRAR HABITACION
    private void jLabelBorrarHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBorrarHabitacionMouseClicked
        try {
         //obtenemos el numero de habitacion y lo transformamos en int con la sentencia integer.parseint ya que es un String lo que que toma del textfiel.  
        int nro_habitacion=Integer.parseInt(jTextFieldNumeroHabitacion.getText());
        //llamamos al procedimiento de la clase habitaciondata que toma el nro_habitacion.
        habitaciondata.borrarHabitacion(nro_habitacion);
        // largamos un mensaje que fue borrado con exito.
        JOptionPane.showMessageDialog(null, "Habitacion borrada con exito");
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al borrar Habitacion: "+ e);
           
        }
        
        
    }//GEN-LAST:event_jLabelBorrarHabitacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Habitacion_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Habitacion_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Habitacion_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Habitacion_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Habitacion_vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupOcupadoDesocupado;
    private javax.swing.JComboBox<String> jComboBoxTipoHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAgregarHabitacion;
    private javax.swing.JLabel jLabelBorrarHabitacion;
    private javax.swing.JLabel jLabelCancelar;
    private javax.swing.JLabel jLabelHuesped;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelMostrarHabitaciones;
    private javax.swing.JLabel jLabelOpciones;
    private javax.swing.JLabel jLabelReserva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonDesocupado;
    private javax.swing.JRadioButton jRadioButtonOcupado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableHabitaciones;
    private javax.swing.JTextField jTextFieldNumeroHabitacion;
    private javax.swing.JTextField jTextFieldPiso;
    private javax.swing.JTextField jTextFieldcantidadHabitacion;
    // End of variables declaration//GEN-END:variables

  

}



