/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.vista;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import AppPackage.AnimationClass;
import hotel.Conexion;
import hotel.modelo.Huesped;
import hotel.modelo.HuespedData;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Reserva_vista extends javax.swing.JFrame {
private HuespedData huespeddata;
private Conexion conexion;
    
    public Reserva_vista() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        conexion = new Conexion("jdbc:mysql://localhost/hotel", "root", "");
        huespeddata = new HuespedData(conexion);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombreApeliido = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelBuscar = new javax.swing.JLabel();
        jLabelCalcularPrecio = new javax.swing.JLabel();
        jLabelReservar = new javax.swing.JLabel();
        jTextFieldFechaEntrada = new javax.swing.JTextField();
        jTextFieldFechaSalida = new javax.swing.JTextField();
        jTextFieldCantidadPersona = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTextFieldPrecioTotal = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabelMenu = new javax.swing.JLabel();
        jLabelHabitacion = new javax.swing.JLabel();
        jLabelHuesped = new javax.swing.JLabel();
        jLabelReservaBusqueda = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelOpciones = new javax.swing.JLabel();
        jLabelCancelar = new javax.swing.JLabel();
        jLabelMinimizar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 490));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 478));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre y Apellido del Huesped");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 220, 20));

        jTextFieldNombreApeliido.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreApeliido.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNombreApeliido.setBorder(null);
        jPanel1.add(jTextFieldNombreApeliido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 270, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(102, 204, 255));
        jSeparator1.setToolTipText("");
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 270, 10));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("D.N.I");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 50, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Domicilio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Correo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Celular");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Fecha Entrada");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Fecha Salida");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cantidad de Persona");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Precio:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 140, 30));

        jTextFieldDNI.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDNI.setBorder(null);
        jPanel1.add(jTextFieldDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, -1));

        jTextFieldDomicilio.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDomicilio.setBorder(null);
        jPanel1.add(jTextFieldDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 230, -1));

        jTextFieldCelular.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCelular.setBorder(null);
        jPanel1.add(jTextFieldCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 240, -1));

        jTextFieldCorreo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCorreo.setBorder(null);
        jPanel1.add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 240, -1));

        jSeparator2.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator2.setForeground(new java.awt.Color(102, 204, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 110, 10));

        jSeparator3.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator3.setForeground(new java.awt.Color(102, 204, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 230, 10));

        jSeparator4.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator4.setForeground(new java.awt.Color(102, 204, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 240, 10));

        jSeparator5.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator5.setForeground(new java.awt.Color(102, 204, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 240, 10));

        jLabelBuscar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_buscar.png"))); // NOI18N
        jLabelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBuscarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelBuscarMouseReleased(evt);
            }
        });
        jPanel1.add(jLabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 40, -1));

        jLabelCalcularPrecio.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelCalcularPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCalcularPrecio.setText("CALCULAR PRECIO");
        jLabelCalcularPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelCalcularPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCalcularPrecioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCalcularPrecioMouseReleased(evt);
            }
        });
        jPanel1.add(jLabelCalcularPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        jLabelReservar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelReservar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelReservar.setText("RESERVAR");
        jLabelReservar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelReservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReservarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelReservarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelReservarMouseReleased(evt);
            }
        });
        jPanel1.add(jLabelReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        jTextFieldFechaEntrada.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFechaEntrada.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldFechaEntrada.setText("DD/MM/AAAA");
        jTextFieldFechaEntrada.setBorder(null);
        jTextFieldFechaEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldFechaEntradaMouseClicked(evt);
            }
        });
        jTextFieldFechaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 90, -1));

        jTextFieldFechaSalida.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFechaSalida.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldFechaSalida.setText("DD/MM/AAAA");
        jTextFieldFechaSalida.setBorder(null);
        jTextFieldFechaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldFechaSalidaMouseClicked(evt);
            }
        });
        jTextFieldFechaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jTextFieldCantidadPersona.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCantidadPersona.setBorder(null);
        jPanel1.add(jTextFieldCantidadPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 60, -1));

        jSeparator6.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator6.setForeground(new java.awt.Color(102, 204, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 60, 10));

        jTextFieldPrecioTotal.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPrecioTotal.setBorder(null);
        jTextFieldPrecioTotal.setEnabled(false);
        jPanel1.add(jTextFieldPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 40, -1));

        jSeparator7.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator7.setForeground(new java.awt.Color(102, 204, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 90, 10));

        jSeparator8.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator8.setForeground(new java.awt.Color(102, 204, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 90, 10));

        jSeparator9.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator9.setForeground(new java.awt.Color(102, 204, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 60, 10));

        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_ventana.png"))); // NOI18N
        jLabelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseReleased(evt);
            }
        });
        jPanel1.add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 30, 40));

        jLabelHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/double-king_ventana.png"))); // NOI18N
        jLabelHabitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHabitacionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelHabitacionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelHabitacionMouseReleased(evt);
            }
        });
        jPanel1.add(jLabelHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 60, 30, 40));

        jLabelHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guest_ventana.png"))); // NOI18N
        jLabelHuesped.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelHuesped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHuespedMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelHuespedMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelHuespedMouseReleased(evt);
            }
        });
        jPanel1.add(jLabelHuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 105, 40, 40));

        jLabelReservaBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_reserva.png"))); // NOI18N
        jLabelReservaBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelReservaBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReservaBusquedaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelReservaBusquedaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelReservaBusquedaMouseReleased(evt);
            }
        });
        jPanel1.add(jLabelReservaBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 160, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 420));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N
        jLabelOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOpcionesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelOpcionesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelOpcionesMouseReleased(evt);
            }
        });
        jPanel2.add(jLabelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, -1, 35));

        jLabelCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jLabelCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCancelarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCancelarMouseReleased(evt);
            }
        });
        jPanel2.add(jLabelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 6, -1, 35));

        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimize_1.png"))); // NOI18N
        jLabelMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 6, -1, 35));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("RESERVA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFechaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaSalidaActionPerformed

    private void jLabelReservarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservarMousePressed
         jLabelReservar.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelReservarMousePressed

    private void jLabelReservarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservarMouseReleased
        jLabelReservar.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelReservarMouseReleased

    private void jLabelCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarMousePressed
     jLabelCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel_in.png")));
    }//GEN-LAST:event_jLabelCancelarMousePressed

    private void jLabelCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarMouseReleased
       jLabelCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png")));
    }//GEN-LAST:event_jLabelCancelarMouseReleased

    private void jLabelCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarMouseClicked
         
        //creo un objeto Icon y le asigno la imagen del icono 
       Icon icono = new ImageIcon(getClass().getResource("/imagenes/logo_ventana.png"));
        
        int dialogoboton = JOptionPane.YES_NO_OPTION;
       int resultado = JOptionPane.showConfirmDialog(null, "Desea salir? ", "Salir",dialogoboton,JOptionPane.QUESTION_MESSAGE,icono);
       //utilizo el if para hacer una comparacion si el usuario da en si sale de la ventana y si le da no sigue trabajando 
       if (resultado==0){
           
          System.exit(0);
       }
    }//GEN-LAST:event_jLabelCancelarMouseClicked

    private void jLabelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseClicked
       this.setState(Reserva_vista.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizarMouseClicked

    private void jLabelBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarMousePressed
        jLabelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_buscar_in.png")));
    }//GEN-LAST:event_jLabelBuscarMousePressed

    private void jLabelBuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarMouseReleased
        jLabelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_buscar.png")));
    }//GEN-LAST:event_jLabelBuscarMouseReleased

    private void jLabelOpcionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpcionesMousePressed
       jLabelOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_in.png")));
    }//GEN-LAST:event_jLabelOpcionesMousePressed

    private void jLabelOpcionesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpcionesMouseReleased
       jLabelOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png")));
    }//GEN-LAST:event_jLabelOpcionesMouseReleased

    private void jLabelCalcularPrecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCalcularPrecioMousePressed
         jLabelCalcularPrecio.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelCalcularPrecioMousePressed

    private void jLabelCalcularPrecioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCalcularPrecioMouseReleased
         
        jLabelCalcularPrecio.setForeground(Color.black);
    }//GEN-LAST:event_jLabelCalcularPrecioMouseReleased

    private void jTextFieldFechaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaEntradaActionPerformed

    private void jTextFieldFechaEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFechaEntradaMouseClicked
      jTextFieldFechaEntrada.setText("");
    }//GEN-LAST:event_jTextFieldFechaEntradaMouseClicked

    private void jTextFieldFechaSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFechaSalidaMouseClicked
        jTextFieldFechaSalida.setText("");
    }//GEN-LAST:event_jTextFieldFechaSalidaMouseClicked

    private void jLabelOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpcionesMouseClicked
       
        //mueve el icono menu a la derecha
        AnimationClass menu =new AnimationClass();
       menu.jLabelXRight(-40, 10, 10, 5, jLabelMenu);
       
       
       //mueve el icono menu a la izquierda
       AnimationClass menuu =new AnimationClass();
       menuu.jLabelXLeft(10, -40, 10, 5, jLabelMenu);
        
       //mueve el icono habitacion a la izquierda
       AnimationClass habitacion =new AnimationClass();
       menu.jLabelXRight(-40, 10, 10, 5, jLabelHabitacion);
       
        
       //mueve el icono habitacion a la derecha
       AnimationClass habitacionn =new AnimationClass();
       menuu.jLabelXLeft(10, -40, 10, 5, jLabelHabitacion);
       
       //mueve el icono huesped a la derecha
       AnimationClass huesped =new AnimationClass();
       menu.jLabelXRight(-40, 10, 10, 5, jLabelHuesped);
       
       //mueve el icono huesped a la izquierda
       AnimationClass huespedd =new AnimationClass();
       menuu.jLabelXLeft(10, -40, 10, 5, jLabelHuesped);
       
       //mueve el icono buscar reserva  a la izquieda
       AnimationClass busquedaReserva = new AnimationClass();
       busquedaReserva.jLabelXRight(-40, 10, 10, 5, jLabelReservaBusqueda);
       
       //mueve el icono buscar reserva a la derecha 
       AnimationClass busquedaReservaa = new AnimationClass();
       busquedaReservaa.jLabelXLeft(10, -40,10,5, jLabelReservaBusqueda);
    }//GEN-LAST:event_jLabelOpcionesMouseClicked

    private void jLabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseClicked
       Menu menu =new Menu();
       menu.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabelMenuMouseClicked

    private void jLabelMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMousePressed
         jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_ventana_in.png")));
    }//GEN-LAST:event_jLabelMenuMousePressed

    private void jLabelMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseReleased
        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_ventana.png")));
    }//GEN-LAST:event_jLabelMenuMouseReleased

    private void jLabelHabitacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHabitacionMousePressed
       jLabelHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/double-king-size_in_ventana.png")));
    }//GEN-LAST:event_jLabelHabitacionMousePressed

    private void jLabelHabitacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHabitacionMouseReleased
        jLabelHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/double-king_ventana.png")));
    }//GEN-LAST:event_jLabelHabitacionMouseReleased

    private void jLabelHuespedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHuespedMousePressed
       jLabelHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guest_in_ventana.png")));
    }//GEN-LAST:event_jLabelHuespedMousePressed

    private void jLabelHuespedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHuespedMouseReleased
      jLabelHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guest_ventana.png")));
    }//GEN-LAST:event_jLabelHuespedMouseReleased

    private void jLabelHuespedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHuespedMouseClicked
         Huesped_vista huesped =new Huesped_vista();
       huesped.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabelHuespedMouseClicked

    private void jLabelHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHabitacionMouseClicked
          Habitacion_vista habitacion =new Habitacion_vista();
      habitacion.setVisible(true);
       dispose(); 
    }//GEN-LAST:event_jLabelHabitacionMouseClicked

    private void jLabelReservaBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservaBusquedaMouseClicked
        ReservaBusqueda_vista busqueda=new  ReservaBusqueda_vista();
      busqueda.setVisible(true);
       dispose(); 

    }//GEN-LAST:event_jLabelReservaBusquedaMouseClicked

    private void jLabelReservaBusquedaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservaBusquedaMousePressed
       jLabelReservaBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_reserva_in.png")));
    }//GEN-LAST:event_jLabelReservaBusquedaMousePressed

    private void jLabelReservaBusquedaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservaBusquedaMouseReleased
         jLabelReservaBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_reserva.png")));
    }//GEN-LAST:event_jLabelReservaBusquedaMouseReleased

    private void jLabelReservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservarMouseClicked
        try {
             String nombreyapellido=jTextFieldNombreApeliido.getText();
        int dni =Integer.parseInt(jTextFieldDNI.getText());
        String domicilio=jTextFieldDomicilio.getText();
        String celular=jTextFieldCelular.getText();
        String correo=jTextFieldCorreo.getText();
        
        Huesped huesped =new Huesped(dni,nombreyapellido,domicilio,celular,correo);
        huespeddata.guardarHuesped(huesped);
        
        JOptionPane.showMessageDialog(null, "Reserva realizada con exito");
        } catch (Exception e) {
             
            
        }
       
        
       
        
        
        
    }//GEN-LAST:event_jLabelReservarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva_vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCalcularPrecio;
    private javax.swing.JLabel jLabelCancelar;
    private javax.swing.JLabel jLabelHabitacion;
    private javax.swing.JLabel jLabelHuesped;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelOpciones;
    private javax.swing.JLabel jLabelReservaBusqueda;
    private javax.swing.JLabel jLabelReservar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextFieldCantidadPersona;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldFechaEntrada;
    private javax.swing.JTextField jTextFieldFechaSalida;
    private javax.swing.JTextField jTextFieldNombreApeliido;
    private javax.swing.JTextField jTextFieldPrecioTotal;
    // End of variables declaration//GEN-END:variables
}
